### PR TITLE
fix(InfiniteHits): change showMore button class to `ais-InfiniteHits-loadMore`

### LINKED ISSUE #406: InfiniteHits the "Show more" button doesn't have the correct style
**Describe the bug 🐛**

The "Show more" of the InfiniteHits doesn't have the correct styles.

**Actual**

screenshot 2018-12-20 at 12 27 20

**Should be**

screenshot 2018-12-20 at 12 28 06

### PR DESCRIPTION
**Pull request by tkrugg**
**Before**
image

**After**
screenshot at jan 14 17-08-21

fixes #406

### CODE REVIEW

File: src/infinite-hits/infinite-hits.ts [hunk 1]
```diff
@@ -32,7 +32,7 @@ import { noop } from '../utils';
       </div>
 
       <button
-        [class]="cx('showMore')"
+        [class]="cx('loadMore')"
```
Comment (samouss) [inline src/infinite-hits/infinite-hits.ts]: The class should also support the `disabled` state (see [specs](https://instantsearch-css.netlify.com/widgets/infinite-hits/)).

Comment (tkrugg) [reply src/infinite-hits/infinite-hits.ts]: ah ok, thanks for giving me the spec link :)
Out of curiosity, why wasn't `:disabled` enough?

Comment (samouss) [reply src/infinite-hits/infinite-hits.ts]: Don't ask me why :D -> https://github.com/algolia/instantsearch-specs/issues/19

File: src/infinite-hits/infinite-hits.ts [hunk 2]
```diff
@@ -32,7 +32,7 @@ import { noop } from '../utils';
       </div>
 
       <button
-        [class]="cx('showMore')"
+        [class]="showMoreClass"
```
Comment (samouss) [inline src/infinite-hits/infinite-hits.ts]: You can probably leverage [`NgClass`](https://angular.io/api/common/NgClass) directive to set the class name rather than relying on a getter.

Comment (tkrugg) [reply src/infinite-hits/infinite-hits.ts]: tried it but ngClass but couldn't get it work with computed properties. There is nowhere an example demonstrating it so I supposed 
```html
<div [ngClass]="{'my-class': true}" /> // works
<div [ngClass]="{[cx('my-class')]: true}" /> // produces a compile error
```
This workaround is also used in [menu widget]( https://github.com/algolia/angular-instantsearch/blob/develop/src/menu/menu.ts#L78-L86)

Comment (tkrugg) [reply src/infinite-hits/infinite-hits.ts]: Actually I can use `class="{{cx('loadMore')}} {{ this.state.isLastPage ? cx('loadMore', 'disabled') : ''}}"` which is maybe better?

Comment (samouss) [reply src/infinite-hits/infinite-hits.ts]: Ah. That's weird. Ok then you can use an array to avoid the extra space when it's not disabled.

Comment (samouss) [reply src/infinite-hits/infinite-hits.ts]: https://github.com/angular/angular/issues/13855

File: src/infinite-hits/infinite-hits.ts [hunk 3]
```diff
@@ -32,7 +32,7 @@ import { noop } from '../utils';
       </div>
 
       <button
-        class="{{cx('loadMore')}} {{this.state.isLastPage ? cx('loadMore', 'disabled') : ''}}"
+        [ngClass]="[cx('loadMore'), this.state.isLastPage ? cx('loadMore', 'disabled') : '']"
```
Comment (francoischalifour) [inline src/infinite-hits/infinite-hits.ts]: You can use the form:

```js
cx('loadMore', { 'disabled': this.state.isLastPage })
```

See: https://github.com/JedWatson/classnames#usage

Comment (samouss) [reply src/infinite-hits/infinite-hits.ts]: Nope it's not this package it's a custom [implementation](https://github.com/algolia/angular-instantsearch/blob/f83117d925bef4dd96d0bafafd1e89e3b56f5cea/src/utils.ts#L1-L25).

Comment (francoischalifour) [reply src/infinite-hits/infinite-hits.ts]: Oh, right...
