### PR TITLE
fix(StarRating): fix overflowing symbols

### LINKED ISSUE #658: Rating menu styling is messed up
**Describe the bug 🐛**

image

**To Reproduce 🔍**

1. Go to https://community.algolia.com/angular-instantsearch/examples/storybook/?selectedKind=RatingMenu&selectedStory=default%20with%20panel%20header&full=0&addons=1&stories=1&panelRight=0

**Environment:**

 - OS: Mac
 - Browser: Chrome / Firefox / Opera
 - Version: respectively 75.0.3770.100 / 68.0  / 62.0.3331.66

### PR DESCRIPTION
**Pull request by tkrugg**
**Summary**

This is fixing a sizing/positioning issue on RatingMenu.
I found that it came from the width and height we are setting on the
symbols.

It seems they've always been there https://github.com/algolia/angular-instantsearch/commit/fa8fe63ef9d2bbad78bc2e34f6b0e998a811f8d3
but they were not specified in [InstantSearch.css](https://instantsearch-css.netlify.com/widgets/rating-menu/)

This will need to be ported to v2

**Result**

Before

before

After
after

Closes #658

### CODE REVIEW

File: src/rating-menu/rating-menu.ts [hunk 1]
```diff
@@ -34,16 +34,12 @@ export type RatingMenuState = {
         <symbol
           id="ais-StarRating-starSymbol"
           viewBox="0 0 24 24"
-          width="24"
-          height="24"
```
Comment (Haroenv) [inline src/rating-menu/rating-menu.ts]: width=height=1em will help it not to be massive, even if the css isn't used

Comment (tkrugg) [reply src/rating-menu/rating-menu.ts]: off record, we discussed that width and height were missing on the non hidden `<svg />` tags, so I added that here 0a79c49
